import Loader from './loader/index';
export { default as Navbar } from './navbar';
export { default as MobileNav } from './navbar/mobile-nav';
export { default as Footer } from './footer';
export { default as HomeVideo } from './homeVideo';
export { default as About } from './about';
export { default as Partners } from './partners';
export { default as WhatWeDo } from './what';
export { default as HowWeMakeIt } from './how';
export { default as ContactAd } from './contactAd';
export { default as Loader } from './loader';